### ISSUE TITLE
CLI for KEGG analysis getting stopped with errors

### ISSUE THREAD

**Issue by harshameghadri** [genescf/GeneSCF#10]
Hi Lal and others,

So I tried to work with geneSCF for KEGG analysis. I had executed the code as mentioned in the docs. The gene list is a csv file with gene names in rows. It works for Go_all not KEGG

Steps i additionally tried,
a. Created a directory manually
b. I gave a chmod 777 so that the program can create and write within directories.

 end up with this error.

![image](https://user-images.githubusercontent.com/14085937/118952653-67879280-b95c-11eb-909c-a075dc814f50.png)

Does anyone have a work around, I can send you the gene list if you would like.

**Comment by genescf** [comment]
Can you please input the complete geneSCF command you used for this run?

**Comment by harshameghadri** [comment]
This is the command i submitted to the cluster

![image](https://user-images.githubusercontent.com/14085937/119123302-b2260f00-ba2f-11eb-9527-17baa2432b59.png)

**Comment by harshameghadri** [comment]
Re-installation with https://github.com/genescf/GeneSCF/releases/download/v1.1/geneSCF-master-v1.1-p2.tar.gz worked.

**Comment by genescf** [comment]
Good to know. All the best. I am closing this issue now.
