### ISSUE TITLE
About the database

### ISSUE THREAD

**Issue by FYanar** [genescf/GeneSCF#12]
There is something I don't understand.
I see that there are 362 genes in geneontology with the number GO:0006936. but the data downloaded with genescf has a total of 104 genes. I guess only direct annotation data is downloaded. I'm wondering is how can I download all data from Gene ontology "without direct annotation". 
Or why should I use this data in this way?

![GO0006936](https://user-images.githubusercontent.com/85994527/122453272-da634800-cfb2-11eb-919d-4a89e90bfb94.PNG)

**Comment by genescf** [comment]
Hi,

You have already contacted us on Twitter and we explained it to you. And yes, GeneSCF only uses direct annotation. Looks like you need more technical details about gene ontology database. You can get more information about the annotations on, http://geneontology.org/docs/go-annotations/

You can also have a look at these [article1](https://gigascience.biomedcentral.com/articles/10.1186/2047-217X-3-4) and [article2](https://academic.oup.com/gigascience/article/7/8/giy103/5069393) for better understanding of how GO term and gene association works.

GeneSCF always suggests to use the direct annotations for gene ontology to avoid burden for the statistical inference of your results.

Hope this information helps. Let us know if you need any help regarding GeneSCF.
