### ISSUE TITLE
NCG database not working

### ISSUE THREAD

**Issue by lubertorubior** [genescf/GeneSCF#14]
Hello and thank you for creating GeneSCF. We are using it with great results, but when we try the NCG database it doesn't work on the latest version. I have reviewed the code and I see it has been disabled, but this is not stated in the documentation. Is it possible to make it work?

Best,
Luis.

**Comment by genescf** [comment]
> Hello and thank you for creating GeneSCF. We are using it with great results, but when we try the NCG database it doesn't work on the latest version. I have reviewed the code and I see it has been disabled, but this is not stated in the documentation. Is it possible to make it work?
> 
> Best, Luis.

Hi Luis,

I will check if I can make it work with the latest version of NCG and get back to you.

**Comment by lubertorubior** [comment]
Cool! Thank you very much for your work.

**Comment by decodebiology** [comment]
There are some formatting issues with different versions of NCG. We could not implement NCG efficiently because of inconsistency in the database structure.
