### ISSUE TITLE
GO uniprot database not working

### ISSUE THREAD

**Issue by mdsufz** [genescf/GeneSCF#15]
Hi,
Thanks for the tool. 
I tried to prepare the database using the following code:
perl prepare_database -db=GO_all -org=goa_uniprot

 But then I get the following errors:
rm: cannot remove '/XX/XX/Desktop/geneSCF-master-source-v1.1-p2/class/lib/db/gene_info_limit.gz': No such file or directory
Downloading GO database....
Extracting goa_uniprot information...

gzip: /XX/XX/Desktop/geneSCF-master-source-v1.1-p2/class/lib/db/goa_uniprot/gene_association.goa_uniprot.gz: unexpected end of file
cat: /XX/XX/Desktop/geneSCF-master-source-v1.1-p2/class/lib/db/goa_uniprot/gene_association.goa_uniprot: No such file or directory
cat: /XX/XX/Desktop/geneSCF-master-source-v1.1-p2/class/lib/db/goa_uniprot/gene_association.goa_uniprot: No such file or directory

rm: cannot remove '/XX/XX/Desktop/geneSCF-master-source-v1.1-p2/class/lib/db/goa_uniprot/gene_association.goa_uniprot': No such file or directory
Database retreived..You are now ready to use geneSCF with organism goa_uniprot from --database GO

After, I try to run the test data using this DB but it keeps giving the same error.

Thanks

**Comment by genescf** [comment]
Hi,

GeneSCF only works with genes specific to organisms. It doesn't support Uniprot/Protein ids. Input genes must be Entrez ids or Gene Symbols.
