### ISSUE TITLE
KEGG hsa database retreiving issue

### ISSUE THREAD

**Issue by ZhenwenYu** [genescf/GeneSCF#16]
Hi, and thanks for creating GeneSCF,

We are using GeneSCF to annotate genes with the KEGG database. However, we occurred an issue that 0 genes can be mapped, as shown in the attached screenshot. We guess there is an issue in retrieving the KEGG database, as the prepare_database retrieves 0 pathways and the kegg_database.txt in class/lib/db/hsa folder is empty. Could you please tell us how to make it works?

Best,
Zhenwen

![GeneSCF KEGG database issue](https://user-images.githubusercontent.com/107731510/178164159-c0a05f9a-30e4-4369-9d7b-537f22853e67.png)

**Comment by genescf** [comment]
Hi,

I have quickly pushed a new sub-release (GeneSCF-v1.1-p3). Please use this new version. It will work. Let me know if you still have the issue.

**Comment by decodebiology** [comment]
Please run as "./geneSCF" instead of "perl geneSCF" and see if it works!!

**Comment by ZhenwenYu** [comment]
Run as "./geneSCF" still has the same illegal division by zero issues in line 599. I have checked the previous issues closed in the discussion, and found the genes mapped in H0.list, are exactly same as in the KEGG database. My Ubuntu system is freshly installed and is Ubuntu 22.04 LTS, and I don't know if other systems are facing the same issue. Maybe my system version is too new or is still lacking some essential environments?
![same issue](https://user-images.githubusercontent.com/107731510/178392125-53fad6e7-713b-4c34-bd20-fbcad7816118.png)

**Comment by genescf** [comment]
Can you try giving full paths to the input file and the output directory?

**Comment by ZhenwenYu** [comment]
input directory: /home/zhenwen/GeneSCF-master/test
output directory: /home/zhenwen/GeneSCF-master/test/output

**Comment by genescf** [comment]
> input directory: /home/zhenwen/GeneSCF-master/test
> output directory: /home/zhenwen/GeneSCF-master/test/output

I meant try giving the full path to geneSCF run.

**Comment by genescf** [comment]
> Run as "./geneSCF" still has the same illegal division by zero issues in line 599. I have checked the previous issues closed in the discussion, and found the genes mapped in H0.list, are exactly same as in the KEGG database. My Ubuntu system is freshly installed and is Ubuntu 22.04 LTS, and I don't know if other systems are facing the same issue. Maybe my system version is too new or is still lacking some essential environments?
> ![same issue](https://user-images.githubusercontent.com/107731510/178392125-53fad6e7-713b-4c34-bd20-fbcad7816118.png)

https://github.com/genescf/GeneSCF/issues/4#issuecomment-437520733

**Comment by ZhenwenYu** [comment]
Inputting the full path doesn't work either. I am using the Ubuntu Linux system and the default gedit text editor, so reasons 1 and 4 don't make sense. Also, we can see from the terminal that many genes matched the KEGG database, so it couldn't be reason 2. Therefore, could there still be some issues in the' prepare_database' module to update the KEGG database? Moreover, Is there someplace we can use the "try" command to skip the illegal division error message and continue?

**Comment by genescf** [comment]
> Inputting the full path doesn't work either. I am using the Ubuntu Linux system and the default gedit text editor, so reasons 1 and 4 don't make sense. Also, we can see from the terminal that many genes matched the KEGG database, so it couldn't be reason 2. Therefore, could there still be some issues in the' prepare_database' module to update the KEGG database? Moreover, Is there someplace we can use the "try" command to skip the illegal division error message and continue?

Hi,

1) First try giving output directly as `/home/zhenwen/GeneSCF-master/test/output/ `NOT `/home/zhenwen/GeneSCF-master/test/output`. There is some weird thing that some time it doesn't accept without "/" in the end.
2) Second, there is possibility that the KEGG database is not updated properly. Can you try `prepare_database` and then try running `geneSCF`.

**Comment by genescf** [comment]
Hi,

Here is the working geneSCF. There was an issue connecting with KEGG. Now it works fine. Let me know. https://github.com/genescf/GeneSCF/archive/refs/tags/v1.1-p3.beta.tar.gz

You can also download this from [latest release](https://github.com/genescf/GeneSCF/releases).

**Comment by ZhenwenYu** [comment]
Thanks a lot for all the helps! Now everything works well with KEGG.
