### ISSUE TITLE
Preparing Database for Rice (ORYZA)

### ISSUE THREAD

**Issue by hafizmtalha** [genescf/GeneSCF#18]
hi, I am trying to prepare database for Oryza species using the following comands.
./prepare_database -db=GO_all -org=dosa (RAPD)
./prepare_database -db=GO_all -org=osa (Refseq)

But the database output files are empty. I am not sure why its doing so. looks like databases are not present link from where it's trying to download. Kindly help me sort this issue.

./prepare_database -db=GO_all -org=osa

Downloading GO database....
Extracting osa information...

gzip: /home/navi/software/GeneSCF/class/lib/db/osa/gene_association.osa.gz: unexpected end of file
cat: /home/navi/software/GeneSCF/class/lib/db/osa/gene_association.osa: No such file or directory
cat: /home/navi/software/GeneSCF/class/lib/db/osa/gene_association.osa: No such file or directory
Updating gene information...
Do not panic. The processing is going on...

gzip: /home/navi/software/GeneSCF/class/lib/db/gene_info.gz: invalid compressed data--format violated
cat: /home/navi/software/GeneSCF/class/lib/db/gene_info: No such file or directory
rm: cannot remove '/home/navi/software/GeneSCF/class/lib/db/gene_info': No such file or directory
rm: cannot remove '/home/navi/software/GeneSCF/class/lib/db/osa/gene_association.osa': No such file or directory
Database retreived..You are now ready to use geneSCF with organism osa from --database GO
Done....2022. 12. 08. (목) 08:59:36 KST

**Comment by genescf** [comment]
Hi,

GeneOntology database doesn't support Oryza species. Please have a look a the following link for species that are supported by GeneOntology, http://current.geneontology.org/products/pages/downloads.html
