### ISSUE TITLE
using "-m=update" yields empty database files?

### ISSUE THREAD

**Issue by joe-marturano** [genescf/GeneSCF#19]
Hi, thank you for this excellent library, I've used it successfully for several years. Today I tried the "-m=update" command with `GO_BP` and `goa_human`, e.g.,:

`./GeneSCF-1.1-p3.beta/geneSCF -m=update -i="./GeneSCF-1.1-p3.beta/io/xxxxx.csv" -o="./GeneSCF-1.1-p3.beta/io/" -t=gid -db=GO_BP -bg=20000 --plot=no, -org=goa_human`

But this seemingly failed to unpack the files correctly. It produced a gzip error:

`/GeneSCF-1.1-p3.beta/class/lib/db/goa_human/gene_association.goa_human.gz: unexpected end of file`

 and yielded empty files (`ls -l`):

<img width="413" alt="image" src="https://github.com/genescf/GeneSCF/assets/79476613/bb24e864-eaad-425d-9a33-b0351642d78c">

 . 

I tried using `/prepare_database` but received the same result. My workaround was a fresh install with the `-m=normal` parameter, which returned successfully. Could you please investigate and advise? Thank you.

**Comment by decodebiology** [comment]
Hi,

The Gene Ontology database was revised with some changes in the database structure. A recent version of GeneSCF will resolve this issue. I assume your fresh installation worked out. If not let me know. Otherwise, I will close this issue in the next 10 days.
